# -*- coding: utf-8 -*-
"""计算机应用方向技能卷（一）～（五）：文档编辑（Word/Excel/PPT）、网页设计的评分规则。
SPECS[卷key][模块id] = [第1小题的检查项列表, 第2小题…]，每小题检查项分值之和 = 该小题分值。
规则按题目要求写；参考答案与题目不一致的地方见 tests/test_skills.py 里的 REFERENCE_DEVIATIONS。"""
from .checks import *  # noqa: F401,F403

SPECS = {}

# ---------------------------------------------------------------- 卷一
SPECS['comp-1'] = {
    'word': [
        [T('纸张宽19.5厘米、高27厘米，左右边距3厘米', 2, w_page(w=19.5, h=27, left=3, right=3)),
         T('“背景图片.jpg”填充为页面背景', 3, w_bg_image())],
        [T('除标题外文本：宋体、四号', 1.5, w_font(sel_body(exclude=['欢迎大家']), east='宋体', size='四号')),
         T('除标题外段前段后均0.5行', 1, w_para(sel_body(exclude=['欢迎大家']), before=0.5, after=0.5)),
         T('“欢迎大家踊跃参加!”方正舒体、小初、红色', 1, w_font(sel_contains('欢迎大家'), east='方正舒体', size='小初', color='红色')),
         T('“欢迎大家踊跃参加!”段前段后1.5行、居中', 1, w_para(sel_contains('欢迎大家'), before=1.5, after=1.5, align='center')),
         T('“主 办：校学工处”右对齐', 0.5, w_para(sel_contains('校学工处'), align='right'))],
        [T('“报告人”字符宽度4字符', 2, w_fit_text('报告人', 4)),
         T('“赵蕈”添加拼音指南', 2, w_ruby('赵蕈')),
         T('“赵蕈”字符间距加宽2磅', 1, w_text_font('赵', char_spacing=2))],
    ],
    'excel': [
        [T('第一行前插入一行（表头下移到第2行）', 1, x_value('A2', '地区')),
         T('A1 输入标题', 1, x_value('A1', '2023年江苏省各市地区生产总值')),
         T('A1:C1 合并', 1, x_merge('A1:C1')),
         T('A1 水平居中、黑体、12号', 2, x_cell_fmt('A1', align='center', font='黑体', size=12))],
        [T('条件：生产总值大于10000', 3, x_cond('B3:B15', 'greaterThan', 10000)),
         T('格式：浅红填充色深红色文本', 2, x_cond('B3:B15', 'greaterThan', 10000, fill='FFC7CE', font_color='9C0006'))],
        [T('增长率为百分比、2位小数', 2, x_numfmt('C3:C15', decimals=2, percent=True)),
         T('按生产总值降序排序', 3, x_sorted('B', 3, 15, desc=True))],
    ],
    'ppt': [
        [T('第2张版式“两栏内容”', 1, p_layout(2, 'twoObj')),
         T('第2张标题红色', 1, p_shape_text(2, ('title',), color='红色')),
         T('左侧文本微软雅黑', 1, p_shape_text(2, ('body', 'obj'), ea='微软雅黑')),
         T('右侧插入 pic.jpg，样式“矩形投影”', 1, p_picture(2, style='shadow'))],
        [T('第3张标题动画：浮入-下浮', 1, p_anim(3, 'title', 47, label='第3张标题')),
         T('第3张文本动画：翻转式由远及近、整批发送', 1, p_anim(3, 'body', 31, by_para='all', label='第3张文本')),
         T('动画顺序：先文本后标题', 1, p_anim_order(3, ['body', 'title'])),
         T('第4张标题：黑体、48磅、加粗、红色(255,0,0)', 1,
           p_shape_text(4, ('title',), ea='黑体', size=48, bold=True, color='FF0000'))],
        [T('删除第1张副标题占位符', 1, p_no_subtitle(1)),
         T('全部幻灯片切换：百叶窗-水平', 1, p_transition_all('blinds', {'dir': 'horz'}, defaults={'dir': 'horz'}))],
    ],
    'web': [
        [T('上框架高度220像素', 1, h_frameset_rows(first=220)),
         T('边界宽度和高度均为1', 1, h_frame_attrs('topFrame', marginwidth='1', marginheight='1')),
         T('边框：是，边框颜色#009900', 1, h_frame_attrs('topFrame', frameborder='yes', bordercolor='#009900')),
         T('背景图像 logo.jpg，横向重复', 1, h_body_bg('topFrame', image='logo.jpg', repeat='repeat-x'))],
        [T('中框架拆分为列：相对1，300像素；左框架名 new、初始网页 new.html', 2,
           h_split('middle.html', 'cols', '*,300', 'new', 'new.html')),
         T('标题下方水平线：居中、宽90%、高2像素', 2, h_hr(file='new.html', align='center', width='90%', size='2'))],
        [T('中右框架插入4行1列表格：宽90%、边框0、居中', 1.5,
           h_table('middleFrame', rows=4, cols=1, width='90%', border='0', align='center')),
         T('每行插入图片1～4.jpg', 1.5, h_table('middleFrame', images=['1.jpg', '2.jpg', '3.jpg', '4.jpg'])),
         T('new 框架标题后插入锚记“景点”', 1, h_anchor(file='new.html', name='景点'))],
        [T('“日月潭景点”：黑体、36px、#990033、居中（CSS规则 a）', 2,
           h_text_style('bottomFrame', '日月潭景点', cls='a', font='黑体', size='36px', color='#990033', align='center')),
         T('链接到锚记“景点”，目标 _new', 1, h_link('bottomFrame', '日月潭景点', href_endswith='#景点', target='_new'))],
    ],
}

# ---------------------------------------------------------------- 卷二
SPECS['comp-2'] = {
    'word': [
        [T('纸张宽27厘米、高20厘米，左右边距3厘米', 2, w_page(w=27, h=20, left=3, right=3)),
         T('“背景图片.jpg”填充为页面背景', 3, w_bg_image())],
        [T('蓝色文本转换为表格（5行3列）', 3, w_table(rows=5, cols=3, near='签到')),
         T('根据窗口自动调整表格', 1, w_table(autofit='window', near='签到')),
         T('表格样式“清单表4-着色2”', 1, w_table(style_has=['ListTable4', 'Accent2'], near='签到'))],
        [T('最后一段：宋体、小四号', 1, w_font(sel_last(), east='宋体', size='小四')),
         T('最后一段：1.5倍行距', 1, w_para(sel_last(), line_mult=1.5)),
         T('首字下沉，下沉4行', 3, w_drop_cap(sel_last(), 4))],
    ],
    'excel': [
        [T('A1:F1 合并', 1, x_merge('A1:F1')),
         T('A1 水平居中、黑体、20号', 2, x_cell_fmt('A1', align='center', font='黑体', size=20)),
         T('工作表重命名为“杭州亚运会奖牌榜”', 1, x_sheet_name('杭州亚运会奖牌榜')),
         T('工作表标签红色', 1, x_tab_color('红色'))],
        [T('F2 输入“总奖牌数”', 1, x_value('F2', '总奖牌数')),
         T('用 SUM 函数求总奖牌数', 2, x_formula(['F%d' % r for r in range(3, 13)], 'SUM')),
         T('按金牌降序、总奖牌数降序排序', 2, x_sorted('C', 3, 12, desc=True, then_col='F'))],
        [T('A2:F12 套用“表样式中等深浅3”', 3, x_table_style('TableStyleMedium3')),
         T('取消自动筛选按钮', 2, x_table_style('TableStyleMedium3', no_filter=True))],
    ],
    'ppt': [
        [T('第一张前插入“标题幻灯片”', 1, p_layout(1, 'title')),
         T('共4张幻灯片', 1, p_slide_count(4)),
         T('主标题：杭州亚运会开幕式，黑体、加粗、60磅、绿色(0,255,0)', 1,
           p_shape_text(1, ('ctrTitle', 'title'), text='杭州亚运会开幕式', ea='黑体', bold=True, size=60, color='00FF00')),
         T('副标题：绿色、智能、节俭、文明，楷体、40磅、红色', 1,
           p_shape_text(1, ('subTitle',), text='绿色、智能、节俭、文明', ea='楷体', size=40, color='红色'))],
        [T('第2张左侧文字：单击、飞入、自左下部、按段落', 1, p_anim(2, 'body', 2, subtype=12, node='click', by_para='p', label='左侧文字')),
         T('第2张右侧图片：飞入、自右下部、上一动画之后', 1, p_anim(2, 'pic', 2, subtype=6, node='after', label='右侧图片')),
         T('第3张图片样式：左“圆形对角，白色”、右“剪去对角，白色”', 2, p_pictures_geom(3, ['round2DiagRect', 'snip2DiagRect']))],
        [T('全部幻灯片切换：揭开', 1, p_transition_all('pull')),
         T('放映方式：观众自行浏览', 1, p_show('browse'))],
    ],
    'web': [
        [T('上框架高度100像素', 0.5, h_frameset_rows(first=100)),
         T('边界宽度和高度均为2', 0.5, h_frame_attrs('topFrame', marginwidth='2', marginheight='2')),
         T('边框：否', 0.5, h_frame_attrs('topFrame', frameborder='no')),
         T('“杭州西湖欢迎您”：楷体、36px、#000000、粗体、居中（CSS规则 a）', 2,
           h_text_style('topFrame', '杭州西湖欢迎您', cls='a', font='楷体', size='36px', color='#000000', align='center', bold=True)),
         T('上框架网页标题“西湖”', 0.5, h_title('topFrame', '西湖'))],
        [T('中框架拆分为列：相对1，350像素；左框架名 new、初始网页 new.html', 1.5,
           h_split('middle.html', 'cols', '*,350', 'new', 'new.html')),
         T('“友情链接：”后插入列表：黄山、故宫、日月潭、西湖，初始选定西湖，不加表单', 2.5,
           h_select(file='new.html', label_text='友情链接：', options=['黄山', '故宫', '日月潭', '西湖'], selected='西湖', list_type=True))],
        [T('中右框架插入4行1列表格：宽95%、边框1', 2, h_table('middleFrame', rows=4, cols=1, width='95%', border='1')),
         T('每行插入图片1～4.jpg', 2, h_table('middleFrame', images=['1.jpg', '2.jpg', '3.jpg', '4.jpg']))],
        [T('“欢迎来到杭州”：幼圆、36px、#006600、居中（CSS规则 b）', 2,
           h_text_style('bottomFrame', '欢迎来到杭州', cls='b', font='幼圆', size='36px', color='#006600', align='center')),
         T('超链接 http://www.hangzhou.gov.cn/，目标 _blank', 1,
           h_link('bottomFrame', '欢迎来到杭州', href='http://www.hangzhou.gov.cn/', target='_blank'))],
    ],
}

# ---------------------------------------------------------------- 卷三
SPECS['comp-3'] = {
    'word': [
        [T('“云动”全部替换为“运动”', 1.5, w_text_count('运动', absent='云动')),
         T('替换后的“运动”橙色、加着重号', 1.5, w_text_font('运动', sel=sel_body(), color='橙色', em=True)),
         T('标题：小二、加粗、蓝色、居中', 2,
           lambda ctx: all_ok([w_font(sel_title(), size='小二', bold=True, color='蓝色')(ctx), w_para(sel_title(), align='center')(ctx)]))],
        [T('左右边距各3厘米', 1, w_page(left=3, right=3)),
         T('正文各段：小四号楷体', 1.5, w_font(sel_body(), east='楷体', size='小四')),
         T('首行缩进2字符', 1, w_para(sel_body(), first_chars=2)),
         T('行距固定值16磅', 1, w_para(sel_body(), line_exact=16)),
         T('段前间距0.5行', 0.5, w_para(sel_body(), before=0.5))],
        [T('第三段边框3磅、橙色个性色2淡色40%；底纹蓝色个性色1淡色40%；图案5%橙色个性色2淡色40%', 5,
           w_para_border_shading(sel_nth(3), 3, 'accent2', '99', 'accent1', '99', 'pct5', 'accent2', '99'))],
    ],
    'excel': [
        [T('A1:L1 合并', 1, x_merge('A1:L1')),
         T('A1 水平居中、微软雅黑、18号', 2, x_cell_fmt('A1', align='center', font='微软雅黑', size=18)),
         T('工作表命名为“AI高考成绩单”', 1, x_sheet_name('AI高考成绩单')),
         T('工作表标签紫色', 1, x_tab_color('紫色'))],
        [T('文科总分（K列）', 1.5, x_formula(['K%d' % r for r in range(3, 12)], 'SUM')),
         T('理科总分（L列）', 1.5, x_formula(['L%d' % r for r in range(3, 12)], 'SUM')),
         T('所有成绩保留1位小数', 2, x_numfmt('B3:L11', decimals=1))],
        [T('簇状柱形图', 2, x_chart()),
         T('图表标题“AI高考成绩比较”', 1.5, x_chart(title='AI高考成绩比较')),
         T('图表放在 A12:L32', 1.5, x_chart(anchor=(0, 11, 11, 31)))],
    ],
    'ppt': [
        [T('第一张前插入“空白”版式幻灯片', 1, p_layout(1, 'blank')),
         T('插入艺术字“人工智能挑战高考”', 1.5, p_wordart(1, '人工智能挑战高考')),
         T('艺术字动画：飞入、自顶部', 1.5, p_anim(1, 'text:人工智能挑战高考', 2, subtype=1, label='艺术字'))],
        [T('第2张版式“内容与标题”', 1, p_layout(2, 'objTx')),
         T('右侧插入 pic.jpg', 1, p_picture(2)),
         T('单击后依次出现：标题→图片→文本', 1, p_anim_order(2, ['title', 'pic', 'body'])),
         T('动画均为飞入、自左侧', 1,
           lambda ctx: all_ok([p_anim(2, t, 2, subtype=8, label=n)(ctx) for t, n in (('title', '标题'), ('pic', '图片'), ('body', '文本'))]))],
        [T('全部幻灯片切换：溶解', 1, p_transition_all('dissolve')),
         T('放映方式：观众自行浏览', 1, p_show('browse'))],
    ],
    'web': [
        [T('上框架高度220像素', 0.5, h_frameset_rows(first=220)),
         T('边界宽度和高度均为3', 0.5, h_frame_attrs('topFrame', marginwidth='3', marginheight='3')),
         T('边框：是，边框颜色#009933', 1, h_frame_attrs('topFrame', frameborder='yes', bordercolor='#009933')),
         T('上框架插入图片 bg.png', 1, h_image('topFrame', src='bg.png')),
         T('上框架网页标题“故宫”', 1, h_title('topFrame', '故宫'))],
        [T('中框架拆分为行：相对1，200像素；上框架名 new、初始网页 new.html', 2,
           h_split('middle.html', 'rows', '*,200', 'new', 'new.html')),
         T('标题下方水平线：居中、宽95%、高2像素', 2, h_hr(file='new.html', align='center', width='95%', size='2'))],
        [T('中下框架插入1行4列表格：宽90%、边框1、居中', 2,
           h_table('middleFrame', rows=1, cols=4, width='90%', border='1', align='center')),
         T('每列插入图片1～4.jpg', 2, h_table('middleFrame', images=['1.jpg', '2.jpg', '3.jpg', '4.jpg']))],
        [T('“北京故宫”：楷体、36px、#990033、居中（CSS规则 a）', 2,
           h_text_style('bottomFrame', '北京故宫', cls='a', font='楷体', size='36px', color='#990033', align='center')),
         T('超链接 https://www.dpm.org.cn/，目标 _new', 1,
           h_link('bottomFrame', '北京故宫', href='https://www.dpm.org.cn/', target='_new'))],
    ],
}

# ---------------------------------------------------------------- 卷四
SPECS['comp-4'] = {
    'word': [
        [T('标题：宋体、小二号、蓝色、居中', 2,
           lambda ctx: all_ok([w_font(sel_title(), east='宋体', size='小二', color='蓝色')(ctx), w_para(sel_title(), align='center')(ctx)])),
         T('正文各段：小四号楷体', 1.5, w_font(sel_body(), east='楷体', size='小四')),
         T('首行缩进2字符', 0.75, w_para(sel_body(), first_chars=2)),
         T('行距1.3倍', 0.75, w_para(sel_body(), line_mult=1.3))],
        [T('第2段分为等宽两栏，加分隔线', 2.5, w_columns(2, True, '莫奈是最崇尚写生')),
         T('图片四周型环绕，放在第3段，高4.6厘米、宽6.3厘米', 2.5,
           w_picture(w_cm=6.3, h_cm=4.6, wrap='wrapSquare', in_text='剑兰花丛'))],
        [T('“莫奈”插入脚注“莫奈，法国画家。”', 2.5, w_footnote('莫奈是最崇尚写生', '莫奈，法国画家。')),
         T('页面边框1磅，橙色个性色2淡色40%', 2.5, w_page_border(1, 'accent2', '99'))],
    ],
    'excel': [
        [T('A1:D1 合并', 1, x_merge('A1:D1')),
         T('A1 水平居中、黑体、20号', 2, x_cell_fmt('A1', align='center', font='黑体', size=20)),
         T('工作表命名为“2023国产十大新能源品牌”', 1, x_sheet_name('2023国产十大新能源品牌')),
         T('工作表标签紫色', 1, x_tab_color('紫色'))],
        [T('C13 用 AVERAGE 求12月平均销量', 1.5, x_formula(['C13'], 'AVERAGE')),
         T('D13 用 SUM 求全年总和', 1.5, x_formula(['D13'], 'SUM')),
         T('C3:D13 保留2位小数', 2, x_numfmt('C3:D13', decimals=2))],
        [T('条件：全年累计销量大于40', 3, x_cond('D3:D12', 'greaterThan', 40)),
         T('格式：浅红色填充', 2, x_cond('D3:D12', 'greaterThan', 40, fill='FFC7CE'))],
    ],
    'ppt': [
        [T('第一张前插入“仅标题”版式幻灯片', 1.5,
           lambda ctx: all_ok([p_layout(1, 'titleOnly')(ctx), p_slide_count(5)(ctx)])),
         T('标题“中国探月工程发射计划”：微软雅黑、67磅、红色(255,0,0)', 2.5,
           p_shape_text(1, ('title',), text='中国探月工程发射计划', ea='微软雅黑', size=67, color='FF0000'))],
        [T('主题“积分”', 1, p_theme('积分')),
         T('第2张标题：擦除、自顶部', 1, p_anim(2, 'title', 22, subtype=1, label='标题')),
         T('左侧文字：劈裂、中央向左右展开', 1, p_anim(2, 'body', 16, subtype=37, label='左侧文字')),
         T('右侧图片：形状、切出', 1, p_anim(2, 'pic', 6, subtype=16, label='右侧图片'))],
        [T('全部幻灯片自动换片时间3秒', 1, p_transition_all(None, adv_ms=3000)),
         T('放映方式：在展台浏览(全屏幕)', 1, p_show('kiosk'))],
    ],
    'web': [
        [T('上框架高度100像素', 0.5, h_frameset_rows(first=100)),
         T('边界宽度和高度均为2', 0.5, h_frame_attrs('topFrame', marginwidth='2', marginheight='2')),
         T('边框：否，边框颜色#666600', 1, h_frame_attrs('topFrame', frameborder='no', bordercolor='#666600')),
         T('网页背景色#999933', 1, h_body_bg('topFrame', color='#999933')),
         T('上框架网页标题“兵马俑”', 1, h_title('topFrame', '兵马俑'))],
        [T('中框架拆分为列：相对1，300像素；左框架名 new、初始网页 new.html', 2,
           h_split('middle.html', 'cols', '*,300', 'new', 'new.html')),
         T('“周围景点搜索：”后插入文本域（宽15）和按钮“搜索”，不加表单', 2,
           h_input(file='new.html', label_text='周围景点搜索：', size=15, button_value='搜索'))],
        [T('中右框架插入4行1列表格：宽95%、边框1，图片1～4.jpg', 2.5,
           h_table('middleFrame', rows=4, cols=1, width='95%', border='1', images=['1.jpg', '2.jpg', '3.jpg', '4.jpg'])),
         T('new 框架标题后插入锚记“景点”', 1.5, h_anchor(file='new.html', name='景点'))],
        [T('“钟山景点”：黑体、36px、#990033、居中（CSS规则 a）', 2,
           h_text_style('bottomFrame', '钟山景点', cls='a', font='黑体', size='36px', color='#990033', align='center')),
         T('链接到锚记“景点”，目标 _new', 1, h_link('bottomFrame', '钟山景点', href_endswith='#景点', target='_new'))],
    ],
}

# ---------------------------------------------------------------- 卷五
P1, P2, P3 = sel_contains('粤港澳'), sel_contains('玛雅人'), sel_contains('历史发展')


def _sel_12():
    def f(d):
        return P1(d) + P2(d)
    f.label = '第1、2段'
    return f


SPECS['comp-5'] = {
    'word': [
        [T('标题改为艺术字，上下型环绕、水平居中', 1.5, w_wordart('巧克力', wrap='wrapTopAndBottom', align_h='center')),
         T('艺术字文本效果：橙色8pt发光、个性色2', 1, w_wordart_glow('巧克力', 8, 'accent2')),
         T('第1、2段“巧克力”替换为“chocolate”', 1.5, w_text_count('chocolate', minimum=2, sel=_sel_12(), absent='巧克力')),
         T('“chocolate”橙色、加着重号', 1, w_text_font('chocolate', sel=_sel_12(), color='橙色', em=True))],
        [T('第1、2段：中文宋体、西文Arial、小四', 1.5, w_font(_sel_12(), east='宋体', ascii='Arial', size='小四')),
         T('第1、2段：首行缩进2字符、固定值28磅、段后0.5行', 1.5, w_para(_sel_12(), first_chars=2, line_exact=28, after=0.5)),
         T('第3段：宋体、小四、蓝色、居中、段后0.5行', 2,
           lambda ctx: all_ok([w_font(P3, east='宋体', size='小四', color='蓝色')(ctx), w_para(P3, align='center', after=0.5)(ctx)]))],
        [T('后5行转换为5行2列表格，居中，根据内容自动调整', 2.5, w_table(rows=5, cols=2, jc='center', autofit='content')),
         T('外框3磅、内框1磅，蓝色单实线', 2.5, w_table_borders(3, 1, '蓝色'))],
    ],
    'excel': [
        [T('A1:E1 合并、水平居中', 1.5, lambda ctx: all_ok([x_merge('A1:E1')(ctx), x_cell_fmt('A1', align='center')(ctx)])),
         T('用 SUM 计算“总工资”列', 2, x_formula(['E%d' % r for r in range(3, 18)], 'SUM')),
         T('E18 用 AVERAGE 计算平均工资', 1.5, x_formula(['E18'], 'AVERAGE'))],
        [T('条件：总工资大于或等于6000', 3, x_cond('E3:E17', 'greaterThanOrEqual', 6000)),
         T('格式：绿色底纹', 2, x_cond('E3:E17', 'greaterThanOrEqual', 6000, fill='00B050'))],
        [T('工作表命名为“职工工资情况表”', 1, x_sheet_name('职工工资情况表')),
         T('自动筛选：基本工资≥2500、总工资≥7000', 4,
           x_filter({1: ('greaterThanOrEqual', 2500), 4: ('greaterThanOrEqual', 7000)}, sheet='职工工资情况表'))],
    ],
    'ppt': [
        [T('第一张前插入“标题幻灯片”', 1, lambda ctx: all_ok([p_layout(1, 'title')(ctx), p_slide_count(4)(ctx)])),
         T('主标题“工作汇报”：微软雅黑、62磅、红色', 1.5,
           p_shape_text(1, ('ctrTitle', 'title'), text='工作汇报', ea='微软雅黑', size=62, color='红色')),
         T('副标题“汇报人：王明”：隶书、40磅、蓝色(0,0,255)', 1.5,
           p_shape_text(1, ('subTitle',), text='汇报人：王明', ea='隶书', size=40, color='0000FF'))],
        [T('第1张背景纯色：蓝色，个性色1，淡色80%', 1.5, p_background(1, 'scheme:accent1:lumMod=20000:lumOff=80000')),
         T('第2张标题动画：弹跳', 1, p_anim(2, 'title', 26, label='标题')),
         T('第3张文本设置项目符号', 0.75, p_bullets(3)),
         T('第3张文本动画：飞入、自右下部', 0.75, p_anim(3, 'body', 2, subtype=6, label='文本'))],
        [T('全部幻灯片切换：悬挂', 1, p_transition_all('prstTrans', {'prst': 'drape'})),
         T('放映方式：观众自行浏览', 1, p_show('browse'))],
    ],
    'web': [
        [T('上框架高度85像素', 0.5, h_frameset_rows(first=85)),
         T('边界宽度和高度均为1', 0.5, h_frame_attrs('topFrame', marginwidth='1', marginheight='1')),
         T('边框：是，边框颜色#999900', 1, h_frame_attrs('topFrame', frameborder='yes', bordercolor='#999900')),
         T('上框架网页标题“桂林山水”', 1, h_title('topFrame', '桂林山水')),
         T('背景图像 bg.jpg，横向重复', 1, h_body_bg('topFrame', image='bg.jpg', repeat='repeat-x'))],
        [T('中框架拆分为行：55%，45%；上框架名 new、初始网页 new.html', 2,
           h_split('middle.html', 'rows', '55%,45%', 'new', 'new.html')),
         T('标题下方水平线：居中、宽90%、高2像素', 2, h_hr(file='new.html', align='center', width='90%', size='2'))],
        [T('中下框架插入1行4列表格：宽100%、边框1、居中', 2,
           h_table('middleFrame', rows=1, cols=4, width='100%', border='1', align='center')),
         T('每列插入图片1～4.jpg', 2, h_table('middleFrame', images=['1.jpg', '2.jpg', '3.jpg', '4.jpg']))],
        [T('底部插入1行2列表格：宽30%、边框1、居中，文字“网站首页”“联系我们”，单元格居中', 2,
           h_table('bottomFrame', rows=1, cols=2, width='30%', border='1', align='center', texts=['网站首页', '联系我们'], cell_align='center')),
         T('“联系我们”链接到 mailto:xuece@126.com，目标 _blank', 1,
           h_link('bottomFrame', '联系我们', href='mailto:xuece@126.com', target='_blank'))],
    ],
}
